spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursDb?serverTimezone=GMT&createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: TRACE
server:
  error:
    include-message: always

jwtSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
jwtExpirationMs: 86400000


flicker:
  apiKey: ff0fdebbe203175138c1cd66461d449c
  apiSecret: cb98ca30bb2c1b49
  appKey: 72157720891997467-240a7dec52f770ea
  appSecret: 70a4d98a531e3141
